#!/bin/bash
#
# Skript zur Erstellung von Hörbert Playlists
#
# Autor: Volkmar Wieland
#
###############################################

echo -n "Bitte wähle die Hörbert Playlist [0..8]: "
read PLAYLIST
TARGET_DIR=/media/${USER}/9016-4EF8/${PLAYLIST}

if [ ! -d $TARGET_DIR ]; then
  mkdir $TARGET_DIR
fi

CONTENT=$(ls $TARGET_DIR)
if [ $(echo CONTENT | wc -l) -gt 1 ]; then
  echo -n "Die Playlist enthält bereits Musik. Möchtest du mehr hinzufügen? [J/n]: "
  read APPEND
  if [ "$APPEND" = "j" ]; then
    INDEX=$(ls $TARGET_DIR | wc -l)
  else
    INDEX=0
    rm -f $TARGET_DIR/*
  fi
fi

cdparanoia -B

for TRACK in *.wav; do
  echo "Verarbeite $TRACK"
  sox --buffer 131072 --multi-threaded --no-glob $TRACK --clobber -r 32000 -b 16 -e signed-integer --no-glob ${INDEX}.WAV remix - gain -n -1.5 bass +1 loudness -1 pad 0 0 dither
  INDEX=$((${INDEX}+1))
  echo "Schreibe ${INDEX}.WAV nach $TARGET_DIR ...
  mv ${INDEX}.WAV $TARGET_DIR
  rm $TRACK
done
